apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 50
        - pause: { duration: 60s }
        - setWeight: 100
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/tedyr10/go-simple-webserver@sha256:e9e939cc118841c45e8920402be9aa20c89c69d55680e5dc44c271d2514335ca
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
